SELECT F.AUTHOR_ID,F.AUTHOR_NAME,F.CATEGORY,SUM(F.PRICE*SALES) AS 'TOTAL_SALES'
FROM 
(SELECT A.AUTHOR_ID,A.AUTHOR_NAME,B.BOOK_ID,B.CATEGORY,B.PRICE,B.PUBLISHED_DATE 
FROM AUTHOR A JOIN BOOK B ON A.AUTHOR_ID=B.AUTHOR_ID) F
JOIN BOOK_SALES B 
ON F.BOOK_ID=B.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID,CATEGORY
ORDER BY 1,3 DESC;